"""Render Great Expectations rule/program code from structured rules.

Two distinct outputs live here, and they are never interchangeable:

- ``render_ge_paste_module`` / ``render_gx_expectation_line`` — an AST-safe
  *fragment* meant to be pasted into the Quality UI's paste panel, parsed by
  ``redibis.contracts.rule_code_parser`` (never executed).
- ``render_full_quality_program`` — a complete, executable Python program
  (imports, rule set, load/validate/main) meant to run standalone, in
  Jupyter, or from a scheduler. It is never round-tripped through the
  AST-safe parser.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any, Optional, Sequence


def _format_literal(value: Any) -> str:
    """Render ``value`` as a Python literal, e.g. for ``key=value`` call args."""
    if isinstance(value, str):
        return repr(value)
    if isinstance(value, bool):
        return "True" if value else "False"
    if value is None:
        return "None"
    if isinstance(value, (list, tuple)):
        inner = ", ".join(_format_literal(v) for v in value)
        return f"[{inner}]"
    if isinstance(value, dict):
        # Proper dict-literal syntax ({"k": v, ...}) — needed so a nested
        # dict value (e.g. meta={...}) is valid, ast.literal_eval-able Python.
        parts = [f"{k!r}: {_format_literal(v)}" for k, v in sorted(value.items(), key=lambda kv: str(kv[0]))]
        return "{" + ", ".join(parts) + "}"
    return repr(value)


def render_gx_expectation_line(
    expectation_type: str,
    *,
    column: Optional[str] = None,
    kwargs: Optional[dict[str, Any]] = None,
    style: str = "qa",
) -> str:
    """Single ``qa.add_gx_expectation`` or ``expect_*`` line with literal kwargs only."""
    kw = dict(kwargs or {})
    if column and "column" not in kw:
        kw["column"] = column
    meta = kw.pop("meta", None)
    parts = [f"expectation_name={_format_literal(expectation_type)}"]
    for key in sorted(kw.keys()):
        parts.append(f"{key}={_format_literal(kw[key])}")
    if meta:
        parts.append(f"meta={_format_literal(meta)}")
    prefix = "qa.add_gx_expectation" if style == "qa" else expectation_type
    if style == "qa":
        return f"qa.add_gx_expectation(\n    {', '.join(parts)})"
    arg_parts = [f"{k}={_format_literal(v)}" for k, v in sorted(kw.items())]
    return f"{expectation_type}(\n    {', '.join(arg_parts)})"


def _kwargs_with_meta(rule: dict[str, Any]) -> dict[str, Any]:
    """Fold a rule's top-level ``meta`` (severity/source/rule id) into kwargs
    so it survives ``render_gx_expectation_line`` instead of being dropped."""
    kwargs = dict(rule.get("kwargs") or {})
    meta = rule.get("meta")
    if meta and "meta" not in kwargs:
        kwargs["meta"] = meta
    return kwargs


def _render_paste_rule(rule: dict[str, Any], column: Optional[str]) -> str:
    """One paste-fragment line: ``qa.add_gx_expectation(...)``, or ``sql_rule(...)``
    for a custom SQL rule (both read back by the AST-safe parser)."""
    from redibis.quality.sql_rules import is_sql_rule, normalize_sql_rule

    if is_sql_rule(rule):
        n = normalize_sql_rule(rule)
        kw = dict(n["kwargs"])
        parts = [_format_literal(kw.pop("sql"))]
        if n.get("column"):
            parts.append(f"column={_format_literal(n['column'])}")
        if n.get("description"):
            parts.append(f"description={_format_literal(n['description'])}")
        parts += [f"{k}={_format_literal(v)}" for k, v in sorted(kw.items())]
        return f"sql_rule(\n    {', '.join(parts)})"
    return render_gx_expectation_line(
        rule.get("rule") or rule.get("expectation_type", ""),
        column=column,
        kwargs=_kwargs_with_meta(rule),
    )


def render_ge_paste_module(rules: Sequence[dict[str, Any]]) -> str:
    """Build ``ge_paste.py`` content — parse-safe, no imports or side effects."""
    lines = [
        "# ge_paste.py — parser-safe quality rules (paste into Redibis Quality UI)",
        "# Generated by redibis; never executed directly.",
        "",
    ]
    table_rules = [r for r in rules if not r.get("column")]
    col_rules: dict[str, list[dict]] = {}
    for r in rules:
        col = r.get("column")
        if col:
            col_rules.setdefault(str(col), []).append(r)

    if table_rules:
        lines.append("# Table-level rules")
        for r in table_rules:
            lines.append(_render_paste_rule(r, None))
            lines.append("")

    for col in sorted(col_rules.keys()):
        lines.append(f"# Column: {col}")
        for r in col_rules[col]:
            lines.append(_render_paste_rule(r, col))
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def rules_from_profiler_expectations(expectations: Sequence[Any]) -> list[dict[str, Any]]:
    """Normalize GE expectation objects to QualityRuleSet-shaped dicts."""
    out: list[dict[str, Any]] = []
    for exp in expectations or []:
        if hasattr(exp, "expectation_type"):
            etype = exp.expectation_type
            kwargs = dict(getattr(exp, "kwargs", {}) or {})
        elif isinstance(exp, dict):
            cfg = exp.get("expectation_config") or exp
            etype = cfg.get("expectation_type") or cfg.get("type")
            kwargs = dict(cfg.get("kwargs") or {})
        else:
            continue
        col = kwargs.get("column")
        out.append({"rule": etype, "column": col, "kwargs": kwargs})
    return out


def render_rules_yaml(rules: Sequence[dict[str, Any]], *, name: Optional[str] = None) -> str:
    import yaml

    payload = {"name": name, "rules": list(rules)}
    return yaml.safe_dump(payload, default_flow_style=False, sort_keys=False)


def _slug(table: str) -> str:
    return table.replace(".", "_").replace("-", "_")


def _pretty_rule_literal(rule: dict[str, Any], indent: int) -> str:
    pad = " " * indent
    inner_pad = " " * (indent + 4)
    lines = [pad + "{"]
    for key in ("rule", "column", "kwargs", "description", "meta"):
        if key not in rule:
            continue
        value = rule[key]
        if key in ("kwargs", "description", "meta") and not value:
            continue
        lines.append(f"{inner_pad}{key!r}: {_format_literal(value)},")
    lines.append(pad + "},")
    return "\n".join(lines)


def _pretty_rules_list(rules: Sequence[dict[str, Any]], indent: int = 12) -> str:
    if not rules:
        return " " * indent + "# no quality rules on the active contract"
    return "\n".join(_pretty_rule_literal(r, indent) for r in rules)


def _grouped_rules_literal(rules: Sequence[dict[str, Any]], indent: int = 4) -> str:
    """Rules as an inline, column-grouped literal list — the block a notebook
    user edits directly. Comments mark each column so hand-editing stays easy."""
    if not rules:
        return " " * indent + "# no quality rules — add your own dicts here"

    pad = " " * indent
    table_level = [r for r in rules if not r.get("column")]
    by_column: dict[str, list[dict[str, Any]]] = {}
    for rule in rules:
        col = rule.get("column")
        if col:
            by_column.setdefault(str(col), []).append(rule)

    blocks: list[str] = []
    if table_level:
        blocks.append(f"{pad}# ── table-level ──")
        blocks.extend(_pretty_rule_literal(r, indent) for r in table_level)
    for col in sorted(by_column):
        blocks.append(f"{pad}# ── column: {col} ──")
        blocks.extend(_pretty_rule_literal(r, indent) for r in by_column[col])
    return "\n".join(blocks)


def detect_runtime_versions() -> tuple[str, str]:
    """Best-effort ``(redibis_version, great_expectations_version)`` for
    provenance in a generated program's header — never raises."""
    redibis_version = ""
    ge_version = ""
    try:
        from importlib.metadata import version as _pkg_version

        redibis_version = _pkg_version("redibis")
    except Exception:  # noqa: BLE001
        pass
    try:
        import great_expectations as _gx

        ge_version = getattr(_gx, "__version__", "")
    except Exception:  # noqa: BLE001
        pass
    return redibis_version, ge_version


def render_full_quality_program(
    *,
    table: str,
    rule_set: Any,
    rule_set_id: str = "",
    rule_set_digest: str = "",
    generated_at: Optional[str] = None,
    redibis_version: str = "",
    ge_version: str = "",
    engine: str = "spark",
) -> str:
    """Render one complete, executable Python program for ``table``'s quality rules.

    Uses the Redibis library + Great Expectations at runtime — this is the
    portable-automation contract: any open-source scheduler (cron, Airflow,
    Dagster, ...) can invoke this file directly, with Redibis only ever a
    ``pip`` dependency, never a required orchestrator. Paste it into Jupyter
    or any IDE, edit the inline ``RULES`` list, and call ``validate(df)`` on a
    DataFrame you already have, or run it standalone via ``main()``.

    ``engine`` defaults to ``"spark"``: real quality verdicts need a full
    partition (a whole business day of transactions), not a few thousand
    driver-side rows, so the program validates a Spark DataFrame in place and
    never calls ``toPandas()``. ``engine="pandas"`` renders the small-file
    local-development variant instead.

    This renderer produces one authoritative program; it is intentionally
    separate from ``render_ge_paste_module``'s AST-safe fragment, which is
    parsed (never executed) by the Quality UI's paste panel.
    """
    engine = (engine or "spark").strip().lower()
    if engine not in ("spark", "pandas"):
        raise ValueError(f"unsupported codegen engine {engine!r} (use 'spark' or 'pandas')")

    slug = _slug(table)
    generated_at = generated_at or datetime.now(timezone.utc).isoformat()
    rule_set_id = rule_set_id or table
    rule_set_digest_display = rule_set_digest or "n/a"
    rules = list(getattr(rule_set, "rules", None) or [])
    rules_literal = _grouped_rules_literal(rules)
    suite_name = f"monitor_{slug}"

    extras = "ge,spark" if engine == "spark" else "ge"
    dep_notes = ["redibis[" + extras + "]" + (f"=={redibis_version}" if redibis_version else "")]
    dep_notes.append(f"great_expectations{'==' + ge_version if ge_version else ''}")
    dep_notes.append("pyspark" if engine == "spark" else "pandas")

    header = f'''#!/usr/bin/env python3
"""
Redibis quality monitor — {table}   [engine: {engine}]

Generated {generated_at} by redibis (Great Expectations {ge_version or "installed version"}).
Rule set id: {rule_set_id!r}  digest: {rule_set_digest_display!r}

Everything this program needs is in this file: edit ``RULES`` below to add,
remove, or retune expectations — no rule JSON/YAML is read at runtime.

Dependencies: {", ".join(dep_notes)}
"""'''

    rules_block = f'''
# ═══════════════════════════════════════════════════════════════════════════
# Quality rules — edit freely. Each dict is one Great Expectations rule:
#   {{"rule": "<expect_*>", "column": "<name or None>", "kwargs": {{...}}}}
# …or a custom SQL rule (the query returns the rows that break it, or one
# number from SELECT COUNT(*)/SUM/AVG/MIN/MAX; ${{object}} is this table):
#   sql_rule("SELECT * FROM ${{object}} WHERE amount < 0", description="…")
# ═══════════════════════════════════════════════════════════════════════════
RULES: list[dict] = [
{rules_literal}
]


def build_rule_set() -> QualityRuleSet:
    """The editable RULES list above, as a Redibis QualityRuleSet."""
    return QualityRuleSet(name={slug!r}, rules=[dict(r) for r in RULES])
'''

    continue_block = f'''

# ═══════════════════════════════════════════════════════════════════════════
# Continue in redibis — author here, hand the rules back to the contract.
#   report = validate(df)          check RULES on a full partition; edit, repeat
#   more = discover_rules(df)      rules redibis finds on this data (a draft)
#   add_rules(more)                …append the new ones to RULES, then validate()
#   RULES.append(sql_rule("SELECT * FROM ${{object}} WHERE …"))   your own SQL rule
#   save_quality_run(df)           → a quality run: `redibis quality-run diff/merge`
# ═══════════════════════════════════════════════════════════════════════════
OUTPUT_DIR = "./reports"   # same store as `redibis … --output-dir`


def discover_rules(df):
    """Rules redibis discovers on this whole DataFrame (a QualityDraft).

    Curate before adding, e.g. ``more.drop(rule_types=SNAPSHOT_RULES)``.
    """
    return author_quality(df, TABLE)


def add_rules(rules) -> int:
    """Append rules (a QualityDraft or RULES-style dicts) to RULES, filling gaps only.

    Great Expectations keeps one expectation per (type, column), so a rule whose
    type and column are already in RULES is skipped — your existing rule wins.
    SQL rules are told apart by their query.
    """
    if hasattr(rules, "to_rules"):
        rules = rules.to_rules()

    def _key(r):
        return (r.get("rule"), r.get("column"),
                (r.get("kwargs") or {{}}).get("sql") or r.get("sql"))

    seen = {{_key(r) for r in RULES}}
    added = 0
    for r in rules:
        key = _key(r)
        if key not in seen:
            RULES.append(dict(r))
            seen.add(key)
            added += 1
    print(f"added {{added}} rule(s); RULES now has {{len(RULES)}}")
    return added


def save_quality_run(df, *, note: str = "authored in a notebook",
                     output_dir: str = OUTPUT_DIR, rules: list | None = None) -> str:
    """Validate RULES on ``df`` and store them as a redibis quality run.

    Nothing reaches the contract until the run is merged
    (``redibis quality-run merge``). For an S3/MinIO store use
    ``QualityAuthor.from_s3(TABLE).save(draft_from_rules(TABLE, RULES, df=df))``.
    """
    draft = draft_from_rules(TABLE, RULES if rules is None else rules, df=df)
    run = QualityAuthor(TABLE, output_dir=output_dir).save(draft, note=note)
    print(f"saved quality run {{run.run_id}}: {{draft.passed}}/{{draft.total}} rules pass on this data")
    print(f"review: redibis quality-run diff {{TABLE}} --run {{run.run_id}} --output-dir {{output_dir}}")
    print(f"merge:  redibis quality-run merge {{TABLE}} --run {{run.run_id}} --output-dir {{output_dir}}")
    return run.run_id


def _in_notebook() -> bool:
    """True inside Jupyter/IPython, where ``__name__`` is also ``"__main__"``."""
    try:
        return get_ipython() is not None  # noqa: F821 - defined by IPython
    except NameError:
        return False
'''

    if engine == "spark":
        return header + f'''
from __future__ import annotations

import argparse
import json

from pyspark.sql import DataFrame, SparkSession

from redibis.quality.authoring import (
    SNAPSHOT_RULES,
    QualityAuthor,
    author_quality,
    draft_from_rules,
    sql_rule,
)
from redibis.quality.gatekeeper import QualityGatekeeper
from redibis.quality.rule_set import QualityRuleSet
from redibis.quality.sql_rules import add_sql_results
from redibis.services.pipeline import apply_quality_rules

TABLE = {table!r}
RULE_SET_ID = {rule_set_id!r}
RULE_SET_DIGEST = {rule_set_digest!r}

# Source defaults — override on the command line or edit here.
SOURCE_TABLE = {table!r}   # catalog table (Hive / Iceberg / Delta / Unity)
SOURCE_PATH = ""           # or a CSV / Parquet / Delta path instead of a table
SOURCE_FORMAT = "parquet"  # used only with SOURCE_PATH
# Validate one full business-day partition, e.g. "txn_date = '2026-08-30'".
# Empty means the whole table — expectations run over every row either way.
PARTITION_FILTER = ""
# "fused": every aggregate rule in ONE Spark job (the rest by Great Expectations on
# the cached frame); "persist": Great Expectations on a cached frame; "ge": as is.
SPARK_MODE = "fused"
{rules_block}

def get_spark(app_name: str = {f"quality_{slug}"!r}) -> SparkSession:
    """Reuse the notebook / spark-submit session, or build a local one."""
    return SparkSession.builder.appName(app_name).getOrCreate()


def load_data(
    spark: SparkSession | None = None,
    *,
    source_table: str = "",
    source_path: str = "",
    source_format: str = "",
    partition_filter: str = "",
) -> DataFrame:
    """Read the dataset as a Spark DataFrame — no row cap, no driver collect.

    In Jupyter you usually already have a DataFrame; pass it straight to
    ``validate(df)`` and skip this entirely.
    """
    spark = spark or get_spark()
    source_table = source_table or SOURCE_TABLE
    source_path = source_path or SOURCE_PATH
    source_format = source_format or SOURCE_FORMAT

    if source_path:
        reader = spark.read.format(source_format)
        if source_format == "csv":
            reader = reader.option("header", "true").option("inferSchema", "true")
        df = reader.load(source_path)
    elif source_table:
        df = spark.table(source_table)
    else:
        raise ValueError("set SOURCE_TABLE or SOURCE_PATH (or pass a DataFrame to validate())")

    predicate = partition_filter if partition_filter else PARTITION_FILTER
    if predicate:
        df = df.filter(predicate)
    return df


def validate(df: DataFrame, rule_set: QualityRuleSet | None = None, *,
             spark_mode: str = SPARK_MODE) -> dict:
    """Run the rules against a Spark DataFrame and return a JSON-ready dict.

    The whole partition is evaluated in the cluster — nothing is sampled or
    collected. ``spark_mode="fused"`` (default) computes the aggregate rules in one
    Spark job; ``"ge"`` runs every rule with Great Expectations.
    """
    rule_set = rule_set or build_rule_set()
    if spark_mode != "ge":
        result = draft_from_rules(TABLE, [dict(r) for r in rule_set.rules]).validate(
            df, spark_mode=spark_mode)
        return _report(result)
    qa = QualityGatekeeper(suite_name={suite_name!r}, in_memory=True)
    qa.attach_dataframe(df, dataset_name={slug!r})
    apply_quality_rules(qa, rule_set, profiler_expectations=[])
    raw = qa.run_tests(stage="standalone", generate_docs=False)
    # Custom SQL rules ({{"rule": "sql", ...}}) run on the same DataFrame.
    return add_sql_results(qa._extract_report_data(raw), df, rule_set.rules, table=TABLE)


def _report(result) -> dict:
    """A redibis validation result in the report shape ``validate`` returns."""
    rows = [{{"rule": r.expectation_type, "column": r.column, "success": bool(r.success),
             "severity": r.severity, "unexpected_count": r.unexpected_count,
             "observed_value": r.observed_value, "partial_unexpected": list(r.partial_unexpected),
             "message": r.message, "rule_id": r.rule_id}} for r in result.results]
    passed = sum(1 for r in rows if r["success"])
    return {{
        "table": TABLE, "engine": result.engine, "stats": result.stats, "results": rows,
        "statistics": {{"evaluated_expectations": len(rows), "successful_expectations": passed,
                        "unsuccessful_expectations": len(rows) - passed,
                        "success_percent": 100.0 * passed / len(rows) if rows else 100.0}},
    }}


def record_partition(df: DataFrame, partition: str, *, store: str = "",
                     spark_mode: str = SPARK_MODE, fingerprint: str = ""):
    """Validate ``df`` (one partition, chosen by you) and store one row per rule in
    the quality result store (``partition_runs`` / ``rule_results``) — Iceberg by
    default, or ``store`` (``s3://…``, ``postgresql://…``, ``file://…``)."""
    from redibis.quality.results import validate_partition

    draft = draft_from_rules(TABLE, [dict(r) for r in RULES])
    return validate_partition(df, TABLE, partition=partition, contract=draft.payload,
                              store=store or None, spark_mode=spark_mode, fingerprint=fingerprint)
{continue_block}

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate {table} against its quality rules (Spark).")
    parser.add_argument("--table", default=SOURCE_TABLE, help="catalog table to validate")
    parser.add_argument("--path", default=SOURCE_PATH, help="CSV/Parquet/Delta path instead of a table")
    parser.add_argument("--format", default=SOURCE_FORMAT, help="format for --path (parquet/csv/delta)")
    parser.add_argument(
        "--partition-filter", default=PARTITION_FILTER,
        help="Spark SQL predicate, e.g. \\"txn_date = '2026-08-30'\\"",
    )
    parser.add_argument("--out", help="write JSON results to this path (in addition to stdout)")
    parser.add_argument("--spark-mode", default=SPARK_MODE, choices=["fused", "persist", "ge"],
                        help="fused: aggregate rules in one Spark job (default)")
    parser.add_argument("--partition", default="",
                        help="record the run in the quality result store as this partition, e.g. dt=2026-08-30")
    parser.add_argument("--results-store", default="",
                        help="result store URI (default: REDIBIS_QUALITY_RESULTS_STORE or Iceberg)")
    parser.add_argument("--fingerprint", default="", help="data version, e.g. the Iceberg snapshot id")
    args = parser.parse_args(argv)

    spark = get_spark()
    df = load_data(
        spark,
        source_table=args.table,
        source_path=args.path,
        source_format=args.format,
        partition_filter=args.partition_filter,
    )
    if args.partition:
        run = record_partition(df, args.partition, store=args.results_store,
                               spark_mode=args.spark_mode, fingerprint=args.fingerprint)
        print(run)
        if args.out:
            with open(args.out, "w", encoding="utf-8") as fh:
                fh.write(json.dumps(run.row(), indent=2, default=str))
        return 0 if run.status == "passed" else 1
    report = validate(df, spark_mode=args.spark_mode)
    payload = json.dumps(report, indent=2, default=str)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(payload)
    print(payload)
    return 0 if all(r.get("success") for r in report.get("results", [])) else 1


if __name__ == "__main__" and not _in_notebook():
    raise SystemExit(main())
'''

    return header + f'''
from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

from redibis.quality.authoring import (
    SNAPSHOT_RULES,
    QualityAuthor,
    author_quality,
    draft_from_rules,
    sql_rule,
)
from redibis.quality.gatekeeper import QualityGatekeeper
from redibis.quality.rule_set import QualityRuleSet
from redibis.quality.sql_rules import add_sql_results
from redibis.services.pipeline import apply_quality_rules

TABLE = {table!r}
RULE_SET_ID = {rule_set_id!r}
RULE_SET_DIGEST = {rule_set_digest!r}
{rules_block}

def load_sample(path: str, rows: int = 5000) -> pd.DataFrame:
    """Load a small CSV/Parquet sample — local development only.

    Pandas caps what you can meaningfully assert; use the Spark variant for a
    real business-day partition.
    """
    p = Path(path)
    if p.suffix.lower() == ".parquet":
        return pd.read_parquet(p).head(rows)
    # Every column as text, exactly as redibis read it when the rules were
    # authored — otherwise "01012345678" becomes 1012345678 and length rules fail.
    return pd.read_csv(p, nrows=rows, dtype=str, keep_default_na=False)


def validate(df: pd.DataFrame, rule_set: QualityRuleSet | None = None) -> dict:
    """Run the rules in-memory (no contract writes) and return a JSON-ready dict."""
    rule_set = rule_set or build_rule_set()
    qa = QualityGatekeeper(suite_name={suite_name!r}, in_memory=True)
    qa.attach_dataframe(df, dataset_name={slug!r})
    apply_quality_rules(qa, rule_set, profiler_expectations=[])
    raw = qa.run_tests(stage="standalone", generate_docs=False)
    # Custom SQL rules ({{"rule": "sql", ...}}) run on the same DataFrame.
    return add_sql_results(qa._extract_report_data(raw), df, rule_set.rules, table=TABLE)
{continue_block}

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate a sample against {table} quality rules.")
    parser.add_argument("--sample", required=True, help="CSV/Parquet sample path")
    parser.add_argument("--rows", type=int, default=5000)
    parser.add_argument("--out", help="write JSON results to this path (in addition to stdout)")
    args = parser.parse_args(argv)

    df = load_sample(args.sample, rows=args.rows)
    report = validate(df)
    payload = json.dumps(report, indent=2, default=str)
    if args.out:
        Path(args.out).write_text(payload, encoding="utf-8")
    print(payload)
    return 0 if all(r.get("success") for r in report.get("results", [])) else 1


if __name__ == "__main__" and not _in_notebook():
    raise SystemExit(main())
'''
