"""Render Great Expectations rule/program code from structured rules.

Two distinct outputs live here, and they are never interchangeable:

- ``render_ge_paste_module`` / ``render_gx_expectation_line`` — an AST-safe
  *fragment* meant to be pasted into the Quality UI's paste panel, parsed by
  ``redibis.contracts.rule_code_parser`` (never executed).
- ``render_full_quality_program`` — a complete, executable Python program
  (imports, rule set, load/validate/main) meant to run standalone, in
  Jupyter, or from a scheduler. It is never round-tripped through the
  AST-safe parser.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any, Optional, Sequence


def _format_literal(value: Any) -> str:
    """Render ``value`` as a Python literal, e.g. for ``key=value`` call args."""
    if isinstance(value, str):
        return repr(value)
    if isinstance(value, bool):
        return "True" if value else "False"
    if value is None:
        return "None"
    if isinstance(value, (list, tuple)):
        inner = ", ".join(_format_literal(v) for v in value)
        return f"[{inner}]"
    if isinstance(value, dict):
        # Proper dict-literal syntax ({"k": v, ...}) — needed so a nested
        # dict value (e.g. meta={...}) is valid, ast.literal_eval-able Python.
        parts = [f"{k!r}: {_format_literal(v)}" for k, v in sorted(value.items(), key=lambda kv: str(kv[0]))]
        return "{" + ", ".join(parts) + "}"
    return repr(value)


def render_gx_expectation_line(
    expectation_type: str,
    *,
    column: Optional[str] = None,
    kwargs: Optional[dict[str, Any]] = None,
    style: str = "qa",
) -> str:
    """Single ``qa.add_gx_expectation`` or ``expect_*`` line with literal kwargs only."""
    kw = dict(kwargs or {})
    if column and "column" not in kw:
        kw["column"] = column
    meta = kw.pop("meta", None)
    parts = [f"expectation_name={_format_literal(expectation_type)}"]
    for key in sorted(kw.keys()):
        parts.append(f"{key}={_format_literal(kw[key])}")
    if meta:
        parts.append(f"meta={_format_literal(meta)}")
    prefix = "qa.add_gx_expectation" if style == "qa" else expectation_type
    if style == "qa":
        return f"qa.add_gx_expectation(\n    {', '.join(parts)})"
    arg_parts = [f"{k}={_format_literal(v)}" for k, v in sorted(kw.items())]
    return f"{expectation_type}(\n    {', '.join(arg_parts)})"


def _kwargs_with_meta(rule: dict[str, Any]) -> dict[str, Any]:
    """Fold a rule's top-level ``meta`` (severity/source/rule id) into kwargs
    so it survives ``render_gx_expectation_line`` instead of being dropped."""
    kwargs = dict(rule.get("kwargs") or {})
    meta = rule.get("meta")
    if meta and "meta" not in kwargs:
        kwargs["meta"] = meta
    return kwargs


def render_ge_paste_module(rules: Sequence[dict[str, Any]]) -> str:
    """Build ``ge_paste.py`` content — parse-safe, no imports or side effects."""
    lines = [
        "# ge_paste.py — parser-safe quality rules (paste into Redibis Quality UI)",
        "# Generated by redibis; never executed directly.",
        "",
    ]
    table_rules = [r for r in rules if not r.get("column")]
    col_rules: dict[str, list[dict]] = {}
    for r in rules:
        col = r.get("column")
        if col:
            col_rules.setdefault(str(col), []).append(r)

    if table_rules:
        lines.append("# Table-level rules")
        for r in table_rules:
            lines.append(render_gx_expectation_line(
                r.get("rule") or r.get("expectation_type", ""),
                column=None,
                kwargs=_kwargs_with_meta(r),
            ))
            lines.append("")

    for col in sorted(col_rules.keys()):
        lines.append(f"# Column: {col}")
        for r in col_rules[col]:
            lines.append(render_gx_expectation_line(
                r.get("rule") or r.get("expectation_type", ""),
                column=col,
                kwargs=_kwargs_with_meta(r),
            ))
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def rules_from_profiler_expectations(expectations: Sequence[Any]) -> list[dict[str, Any]]:
    """Normalize GE expectation objects to QualityRuleSet-shaped dicts."""
    out: list[dict[str, Any]] = []
    for exp in expectations or []:
        if hasattr(exp, "expectation_type"):
            etype = exp.expectation_type
            kwargs = dict(getattr(exp, "kwargs", {}) or {})
        elif isinstance(exp, dict):
            cfg = exp.get("expectation_config") or exp
            etype = cfg.get("expectation_type") or cfg.get("type")
            kwargs = dict(cfg.get("kwargs") or {})
        else:
            continue
        col = kwargs.get("column")
        out.append({"rule": etype, "column": col, "kwargs": kwargs})
    return out


def render_rules_yaml(rules: Sequence[dict[str, Any]], *, name: Optional[str] = None) -> str:
    import yaml

    payload = {"name": name, "rules": list(rules)}
    return yaml.safe_dump(payload, default_flow_style=False, sort_keys=False)


def _slug(table: str) -> str:
    return table.replace(".", "_").replace("-", "_")


def _pretty_rule_literal(rule: dict[str, Any], indent: int) -> str:
    pad = " " * indent
    inner_pad = " " * (indent + 4)
    lines = [pad + "{"]
    for key in ("rule", "column", "kwargs", "meta"):
        if key not in rule:
            continue
        value = rule[key]
        if key in ("kwargs", "meta") and not value:
            continue
        lines.append(f"{inner_pad}{key!r}: {_format_literal(value)},")
    lines.append(pad + "},")
    return "\n".join(lines)


def _pretty_rules_list(rules: Sequence[dict[str, Any]], indent: int = 12) -> str:
    if not rules:
        return " " * indent + "# no quality rules on the active contract"
    return "\n".join(_pretty_rule_literal(r, indent) for r in rules)


def _grouped_rules_literal(rules: Sequence[dict[str, Any]], indent: int = 4) -> str:
    """Rules as an inline, column-grouped literal list — the block a notebook
    user edits directly. Comments mark each column so hand-editing stays easy."""
    if not rules:
        return " " * indent + "# no quality rules — add your own dicts here"

    pad = " " * indent
    table_level = [r for r in rules if not r.get("column")]
    by_column: dict[str, list[dict[str, Any]]] = {}
    for rule in rules:
        col = rule.get("column")
        if col:
            by_column.setdefault(str(col), []).append(rule)

    blocks: list[str] = []
    if table_level:
        blocks.append(f"{pad}# ── table-level ──")
        blocks.extend(_pretty_rule_literal(r, indent) for r in table_level)
    for col in sorted(by_column):
        blocks.append(f"{pad}# ── column: {col} ──")
        blocks.extend(_pretty_rule_literal(r, indent) for r in by_column[col])
    return "\n".join(blocks)


def detect_runtime_versions() -> tuple[str, str]:
    """Best-effort ``(redibis_version, great_expectations_version)`` for
    provenance in a generated program's header — never raises."""
    redibis_version = ""
    ge_version = ""
    try:
        from importlib.metadata import version as _pkg_version

        redibis_version = _pkg_version("redibis")
    except Exception:  # noqa: BLE001
        pass
    try:
        import great_expectations as _gx

        ge_version = getattr(_gx, "__version__", "")
    except Exception:  # noqa: BLE001
        pass
    return redibis_version, ge_version


def render_full_quality_program(
    *,
    table: str,
    rule_set: Any,
    rule_set_id: str = "",
    rule_set_digest: str = "",
    generated_at: Optional[str] = None,
    redibis_version: str = "",
    ge_version: str = "",
    engine: str = "spark",
) -> str:
    """Render one complete, executable Python program for ``table``'s quality rules.

    Uses the Redibis library + Great Expectations at runtime — this is the
    portable-automation contract: any open-source scheduler (cron, Airflow,
    Dagster, ...) can invoke this file directly, with Redibis only ever a
    ``pip`` dependency, never a required orchestrator. Paste it into Jupyter
    or any IDE, edit the inline ``RULES`` list, and call ``validate(df)`` on a
    DataFrame you already have, or run it standalone via ``main()``.

    ``engine`` defaults to ``"spark"``: real quality verdicts need a full
    partition (a whole business day of transactions), not a few thousand
    driver-side rows, so the program validates a Spark DataFrame in place and
    never calls ``toPandas()``. ``engine="pandas"`` renders the small-file
    local-development variant instead.

    This renderer produces one authoritative program; it is intentionally
    separate from ``render_ge_paste_module``'s AST-safe fragment, which is
    parsed (never executed) by the Quality UI's paste panel.
    """
    engine = (engine or "spark").strip().lower()
    if engine not in ("spark", "pandas"):
        raise ValueError(f"unsupported codegen engine {engine!r} (use 'spark' or 'pandas')")

    slug = _slug(table)
    generated_at = generated_at or datetime.now(timezone.utc).isoformat()
    rule_set_id = rule_set_id or table
    rule_set_digest_display = rule_set_digest or "n/a"
    rules = list(getattr(rule_set, "rules", None) or [])
    rules_literal = _grouped_rules_literal(rules)
    suite_name = f"monitor_{slug}"

    extras = "ge,spark" if engine == "spark" else "ge"
    dep_notes = ["redibis[" + extras + "]" + (f"=={redibis_version}" if redibis_version else "")]
    dep_notes.append(f"great_expectations{'==' + ge_version if ge_version else ''}")
    dep_notes.append("pyspark" if engine == "spark" else "pandas")

    header = f'''#!/usr/bin/env python3
"""
Redibis quality monitor — {table}   [engine: {engine}]

Generated {generated_at} by redibis (Great Expectations {ge_version or "installed version"}).
Rule set id: {rule_set_id!r}  digest: {rule_set_digest_display!r}

Everything this program needs is in this file: edit ``RULES`` below to add,
remove, or retune expectations — no rule JSON/YAML is read at runtime.

Dependencies: {", ".join(dep_notes)}
"""'''

    rules_block = f'''
# ═══════════════════════════════════════════════════════════════════════════
# Quality rules — edit freely. Each dict is one Great Expectations rule:
#   {{"rule": "<expect_*>", "column": "<name or None>", "kwargs": {{...}}}}
# ═══════════════════════════════════════════════════════════════════════════
RULES: list[dict] = [
{rules_literal}
]


def build_rule_set() -> QualityRuleSet:
    """The editable RULES list above, as a Redibis QualityRuleSet."""
    return QualityRuleSet(name={slug!r}, rules=[dict(r) for r in RULES])
'''

    if engine == "spark":
        return header + f'''
from __future__ import annotations

import argparse
import json

from pyspark.sql import DataFrame, SparkSession

from redibis.quality.gatekeeper import QualityGatekeeper
from redibis.quality.rule_set import QualityRuleSet
from redibis.services.pipeline import apply_quality_rules

TABLE = {table!r}
RULE_SET_ID = {rule_set_id!r}
RULE_SET_DIGEST = {rule_set_digest!r}

# Source defaults — override on the command line or edit here.
SOURCE_TABLE = {table!r}   # catalog table (Hive / Iceberg / Delta / Unity)
SOURCE_PATH = ""           # or a CSV / Parquet / Delta path instead of a table
SOURCE_FORMAT = "parquet"  # used only with SOURCE_PATH
# Validate one full business-day partition, e.g. "txn_date = '2026-08-30'".
# Empty means the whole table — expectations run over every row either way.
PARTITION_FILTER = ""
{rules_block}

def get_spark(app_name: str = {f"quality_{slug}"!r}) -> SparkSession:
    """Reuse the notebook / spark-submit session, or build a local one."""
    return SparkSession.builder.appName(app_name).getOrCreate()


def load_data(
    spark: SparkSession | None = None,
    *,
    source_table: str = "",
    source_path: str = "",
    source_format: str = "",
    partition_filter: str = "",
) -> DataFrame:
    """Read the dataset as a Spark DataFrame — no row cap, no driver collect.

    In Jupyter you usually already have a DataFrame; pass it straight to
    ``validate(df)`` and skip this entirely.
    """
    spark = spark or get_spark()
    source_table = source_table or SOURCE_TABLE
    source_path = source_path or SOURCE_PATH
    source_format = source_format or SOURCE_FORMAT

    if source_path:
        reader = spark.read.format(source_format)
        if source_format == "csv":
            reader = reader.option("header", "true").option("inferSchema", "true")
        df = reader.load(source_path)
    elif source_table:
        df = spark.table(source_table)
    else:
        raise ValueError("set SOURCE_TABLE or SOURCE_PATH (or pass a DataFrame to validate())")

    predicate = partition_filter if partition_filter else PARTITION_FILTER
    if predicate:
        df = df.filter(predicate)
    return df


def validate(df: DataFrame, rule_set: QualityRuleSet | None = None) -> dict:
    """Run the rules against a Spark DataFrame and return a JSON-ready dict.

    Great Expectations attaches to the Spark DataFrame directly, so the whole
    partition is evaluated in the cluster — nothing is sampled or collected.
    """
    rule_set = rule_set or build_rule_set()
    qa = QualityGatekeeper(suite_name={suite_name!r}, in_memory=True)
    qa.attach_dataframe(df, dataset_name={slug!r})
    apply_quality_rules(qa, rule_set, profiler_expectations=[])
    raw = qa.run_tests(stage="standalone", generate_docs=False)
    return qa._extract_report_data(raw)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate {table} against its quality rules (Spark).")
    parser.add_argument("--table", default=SOURCE_TABLE, help="catalog table to validate")
    parser.add_argument("--path", default=SOURCE_PATH, help="CSV/Parquet/Delta path instead of a table")
    parser.add_argument("--format", default=SOURCE_FORMAT, help="format for --path (parquet/csv/delta)")
    parser.add_argument(
        "--partition-filter", default=PARTITION_FILTER,
        help="Spark SQL predicate, e.g. \\"txn_date = '2026-08-30'\\"",
    )
    parser.add_argument("--out", help="write JSON results to this path (in addition to stdout)")
    args = parser.parse_args(argv)

    spark = get_spark()
    df = load_data(
        spark,
        source_table=args.table,
        source_path=args.path,
        source_format=args.format,
        partition_filter=args.partition_filter,
    )
    report = validate(df)
    payload = json.dumps(report, indent=2, default=str)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(payload)
    print(payload)
    return 0 if all(r.get("success") for r in report.get("results", [])) else 1


if __name__ == "__main__":
    raise SystemExit(main())
'''

    return header + f'''
from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

from redibis.quality.gatekeeper import QualityGatekeeper
from redibis.quality.rule_set import QualityRuleSet
from redibis.services.pipeline import apply_quality_rules

TABLE = {table!r}
RULE_SET_ID = {rule_set_id!r}
RULE_SET_DIGEST = {rule_set_digest!r}
{rules_block}

def load_sample(path: str, rows: int = 5000) -> pd.DataFrame:
    """Load a small CSV/Parquet sample — local development only.

    Pandas caps what you can meaningfully assert; use the Spark variant for a
    real business-day partition.
    """
    p = Path(path)
    if p.suffix.lower() == ".parquet":
        return pd.read_parquet(p).head(rows)
    return pd.read_csv(p, nrows=rows)


def validate(df: pd.DataFrame, rule_set: QualityRuleSet | None = None) -> dict:
    """Run the rules in-memory (no contract writes) and return a JSON-ready dict."""
    rule_set = rule_set or build_rule_set()
    qa = QualityGatekeeper(suite_name={suite_name!r}, in_memory=True)
    qa.attach_dataframe(df, dataset_name={slug!r})
    apply_quality_rules(qa, rule_set, profiler_expectations=[])
    raw = qa.run_tests(stage="standalone", generate_docs=False)
    return qa._extract_report_data(raw)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate a sample against {table} quality rules.")
    parser.add_argument("--sample", required=True, help="CSV/Parquet sample path")
    parser.add_argument("--rows", type=int, default=5000)
    parser.add_argument("--out", help="write JSON results to this path (in addition to stdout)")
    args = parser.parse_args(argv)

    df = load_sample(args.sample, rows=args.rows)
    report = validate(df)
    payload = json.dumps(report, indent=2, default=str)
    if args.out:
        Path(args.out).write_text(payload, encoding="utf-8")
    print(payload)
    return 0 if all(r.get("success") for r in report.get("results", [])) else 1


if __name__ == "__main__":
    raise SystemExit(main())
'''
