"""Airflow DAG string templates for continuous quality monitoring."""

from __future__ import annotations

import re
from typing import Optional


def dag_id_for_table(table: str, *, event: bool = False) -> str:
    slug = table.replace(".", "_").replace("-", "_")
    return f"redibis_quality_{slug}_event" if event else f"redibis_quality_{slug}"


def _sample_path(table: str, sample_root: str) -> str:
    slug = table.replace(".", "_")
    return f'"{sample_root}/{slug}.csv"'


def render_table_dag(
    *,
    table: str,
    schedule: Optional[str] = "0 6 * * *",
    sample_root: str = "${REDIBIS_SAMPLE_ROOT}",
    config_path: str = "${REDIBIS_CONFIG:-/etc/redibis/redibis.yaml}",
    output_dir: str = "${REDIBIS_OUTPUT_DIR:-/var/redibis/reports}",
    trigger_only: bool = False,
    rows: int = 5000,
    runner: str = "cli",
    program: str = "",
    partition_filter: str = "",
    spark_submit: str = "${SPARK_SUBMIT:-spark-submit}",
) -> str:
    """Return Python source for a thin BashOperator DAG (no airflow import in redibis core).

    ``runner="spark_submit"`` wraps the deployment package's authoritative Spark
    program, which validates the **whole** partition in the cluster. The default
    ``runner="cli"`` runs ``redibis quality-monitor run`` against a bounded
    driver-side sample — useful as a smoke check, not as a full-dataset verdict.
    """
    slug = table.replace(".", "_")
    dag_id = dag_id_for_table(table, event=trigger_only)
    sched = "None" if schedule is None or trigger_only else repr(schedule)
    runner = (runner or "cli").strip().lower()

    if runner == "spark_submit":
        program = program or f"{slug}_quality.py"
        predicate = partition_filter or "${REDIBIS_PARTITION_FILTER:-}"
        header_note = (
            f"Runs the package's authoritative Spark program via spark-submit, so the\n"
            f"complete partition is validated in the cluster (no driver-side sampling)."
        )
        bash = f"""
set -euo pipefail
cd "${{REDIBIS_PACKAGE_DIR:-$AIRFLOW_HOME/dags/{slug}-monitoring}}"
{spark_submit} {program} \\
  --table {table} \\
  --partition-filter "{predicate}" \\
  --out "{output_dir}/{slug}_quality_run.json"
""".strip()
    else:
        sample = _sample_path(table, sample_root)
        header_note = (
            f"Runs `redibis quality-monitor run` against a bounded {rows}-row sample.\n"
            f"This is a smoke check — use the package's Spark program (spark-submit)\n"
            f"to validate a complete business-day partition."
        )
        bash = f"""
set -euo pipefail
export REDIBIS_CONFIG="{config_path}"
SAMPLE={sample}
redibis quality-monitor run {table} \\
  --sample "$SAMPLE" \\
  --rows {rows} \\
  --config "$REDIBIS_CONFIG" \\
  --output-dir "{output_dir}" \\
  --json
""".strip()

    return f'''"""
Auto-generated by redibis — continuous quality monitor for {table}.
Deploy to $AIRFLOW_HOME/dags/ ; requires redibis CLI on the worker PATH.

{header_note}
"""
from __future__ import annotations

from datetime import datetime, timedelta

try:
    from airflow import DAG
    from airflow.operators.bash import BashOperator
except ImportError as exc:  # pragma: no cover
    raise ImportError("Install apache-airflow to parse this DAG module") from exc

DAG_ID = {dag_id!r}
TABLE = {table!r}

default_args = {{
    "owner": "redibis",
    "depends_on_past": False,
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
}}

with DAG(
    dag_id=DAG_ID,
    default_args=default_args,
    description=f"Redibis quality monitor for {{TABLE}}",
    schedule={sched},
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["redibis", "quality", "monitor"],
) as dag:
    BashOperator(
        task_id="monitor_run",
        bash_command={bash!r},
    )
'''
